### ISSUE TITLE
update + push support in spark-mongodb ??

### ISSUE THREAD

**Issue by gupash** [Stratio/Spark-MongoDB#123]
Hi,
I want to inserting a new entry in embedded field in existing document in mongodb using spark.

##### Example
```
Blog {  
    id:"001"  
    title:"This is a test blog",  
    content:"...."  
    comments:[{title:"comment1",content:".."},{title:"comment2",content:"..."}]      
}
```

##### What I want to do
`db.blogs.update({id:"001"}, {$push:{comments:{title:"commentX",content:".."}}});`

Is it possible currently in this library? If not, can you please point me to the right direction.

Thanks in Advance

**Comment by pfcoperez** [comment]
Spark is an analysis tool so that its data sources connectors interfaces are not designed for operational manipulation.

Tools leveraging and expanding SparkSQL such as [Stratio Crossdata](https://github.com/Stratio/Crossdata) are able to provide native access to data sources and an expanded SparkSQL language. These two features enable the possibility of providing operational queries which, in fact, is within Crossdata development road map.

In the meanwhile, you'll need a MongoDB client library like [Casbah](https://mongodb.github.io/casbah/). I would use this library since it is a current dependency of Spark-MongoDB.

**Comment by pfcoperez** [comment]
I've checked it and found that the SPARK developer API for relations does include an operational insert entry point which could be use to insert or update an entire row, a MongoDB document into the collection:

```
@DeveloperApi
trait InsertableRelation {
  def insert(data: DataFrame, overwrite: Boolean): Unit
}
```

However, sub-document update goes beyond its contract scope.

**Comment by gupash** [comment]
Hi,
Not sure how will we use the Developer API you mentioned above. But anyways I was able to do the nested Insert operation in update query, using the Casbah library you mentioned. 

Thanks for your help :)

**Comment by pfcoperez** [comment]
@gupash Great, anytime!
